# docker-compose.yml - ETAPA 5

version: '3.8'

services:
  # API Principal
  api:
    build: 
      context: ./services
      dockerfile: Dockerfile
    container_name: odonto-api
    ports:
      - "8000:8000"
    environment:
      # Database
      - DATABASE_URL=postgresql://odonto:odonto123@db:5432/odonto_db
      
      # WhatsApp/Evolution
      - EVOLUTION_API_URL=http://evolution:8080
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY:-your_key_here}
      - EVOLUTION_INSTANCE=${EVOLUTION_INSTANCE:-odonto_instance}
      
      # LLM
      - LLM_PROVIDER=${LLM_PROVIDER:-anthropic}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - LLM_MODEL=${LLM_MODEL:-claude-3-haiku-20240307}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS:-500}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.7}
      
      # Google Calendar
      - GOOGLE_AUTH_MODE=${GOOGLE_AUTH_MODE:-service_account}
      - GOOGLE_CREDENTIALS_JSON=/secrets/google-credentials.json
      - GOOGLE_CALENDAR_ID=${GOOGLE_CALENDAR_ID:-primary}
      - CLINIC_TIMEZONE=${CLINIC_TIMEZONE:-America/Sao_Paulo}
      
      # Disponibilidade
      - AVAIL_LOOKAHEAD_DAYS=${AVAIL_LOOKAHEAD_DAYS:-14}
      - DEFAULT_SLOT_MINUTES=${DEFAULT_SLOT_MINUTES:-30}
      - WINDOW_MANHA=${WINDOW_MANHA:-08:00-12:00}
      - WINDOW_TARDE=${WINDOW_TARDE:-12:00-18:00}
      - WINDOW_NOITE=${WINDOW_NOITE:-18:00-21:00}
      
      # API Config
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      
    volumes:
      - ./services:/app
      - ./secrets:/secrets:ro  # Read-only para segurança
    depends_on:
      db:
        condition: service_healthy
    networks:
      - odonto-network
    restart: unless-stopped
    
  # Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: odonto-db
    environment:
      - POSTGRES_USER=odonto
      - POSTGRES_PASSWORD=odonto123
      - POSTGRES_DB=odonto_db
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups  # Para backups do banco
    ports:
      - "5432:5432"  # Expor para desenvolvimento, remover em produção
    networks:
      - odonto-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odonto -d odonto_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  # Evolution API (WhatsApp)
  evolution:
    image: evolution-api:latest
    container_name: odonto-evolution
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - AUTHENTICATION_API_KEY=${EVOLUTION_API_KEY:-your_key_here}
      - AUTHENTICATION_INSTANCE=${EVOLUTION_INSTANCE:-odonto_instance}
    volumes:
      - evolution_data:/evolution/instances
    networks:
      - odonto-network
    restart: unless-stopped
    
  # pgAdmin (opcional, para desenvolvimento)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: odonto-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@odonto.local
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - "8090:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - odonto-network
    profiles:
      - dev  # Só inicia com: docker-compose --profile dev up
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
  evolution_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  odonto-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16